name: Branch name
on:
  workflow_dispatch:


jobs:

  run: |
      runs-on: ubuntu-latest
      steps: 
      - name: baby steps
        run: echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
      - name: more baby steps
        run: |
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/} &&
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
