name: Branch name
  run: |
      echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
      echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/} 
      echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
