name: Branch name
on:
  workflow_dispatch:


jobs:
  dump-version: 
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag listshop-webclient:1.2.4
      - name: ensure fresh docker login by logging out
        run: docker logout
      - name: push docker image using maven
        run: docker push --username=${{ secrets.DOCKER_HUB_USERNAME }} --password=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
        
