name: Branch name
on:
  workflow_dispatch:


jobs:
  dump-version: 
      runs-on: ubuntu-latest
      steps: 
      - name: baby steps
        run: echo ${GITHUB_REF#refs/*/}
      - name: more baby steps
        run: echo ${GITHUB_REF#refs/heads/} 
      - name: even more
        run: echo ${GITHUB_REF#refs/tags/}
        
